### ISSUE TITLE
BUG: Fresh run does not work, broken config!

### ISSUE THREAD

**Issue by alibama** [louisgv/local.ai#95] opened 2023-08-17 00:09 UTC
<img width="1260" alt="Screenshot 2023-08-16 at 8 06 31 PM" src="https://github.com/louisgv/local.ai/assets/911386/af127233-a9ed-4076-a7eb-05c1a3dc057b">
so this is what i'm seeing on the back end.... and when i got to localhost:8080 i see "pong" as the response, however when i try to use the models in flowise i'm not getting anything, just 404's

also the "New Thread" function doesn't seem to work or do anything.  it's a vanilla install, i've downloaded a couple of models and those seem to be in place, however nothing else seems to work = advice appreciated

**Comment by louisgv** [comment] 2023-08-17 07:37
@alibama did you allow it to access your file system? The thread feature creates file within your system to store the dialog. Also I think GPU inference doesn't work until we update upstream llm to handle the issue

**Comment by alibama** [comment] 2023-08-17 15:47
<img width="1264" alt="Screenshot 2023-08-17 at 11 46 27 AM" src="https://github.com/louisgv/local.ai/assets/911386/a4c3fcdb-1a37-4707-afd1-3e762613ccf2">
<img width="1267" alt="Screenshot 2023-08-17 at 11 46 05 AM" src="https://github.com/louisgv/local.ai/assets/911386/5f34a48a-2bd7-430f-b88d-21a0e14b2870">
<img width="1266" alt="Screenshot 2023-08-17 at 11 45 46 AM" src="https://github.com/louisgv/local.ai/assets/911386/4d2d7d4e-f3de-4906-b07c-7ec511944a8e">

so I've chown'ed everything over to local user and it's running smoothly (returns pong) but still doesn't see the models from the server side...

gpu is off...

**Comment by alibama** [comment] 2023-08-17 15:49
<img width="1204" alt="Screenshot 2023-08-17 at 11 48 28 AM" src="https://github.com/louisgv/local.ai/assets/911386/16ce223a-2794-4662-bd95-4b9e8f43af3f">
here's what happens when i go to http://localhost:8080/v1/models in postman

**Comment by louisgv** [comment] 2023-08-17 23:06
@alibama Check the wiki for where the endpoint route: https://github.com/louisgv/local.ai/wiki

local doesn't prefix version, it's just `/completions` :d.... (which prob  need to be fixed in the future to align with more client)

**Comment by alibama** [comment] 2023-08-18 19:02
thanks!  i'm working on getting this running with langflow/flowise & still bumping in to issues... i've moved over to localai's docker instance and that's working well enough for now

**Comment by scott-mackenzie** [comment] 2023-09-15 01:54
![Screenshot 2023-09-14 at 9 34 24 PM](https://github.com/louisgv/local.ai/assets/1774915/f45beb33-1faf-45cd-b66d-6cd67461ba92)

 Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac14,6
      Model Number: Z179000H4LL/A
      Chip: Apple M2 Max
      Total Number of Cores: 12 (8 performance and 4 efficiency)
      Memory: 96 GB
      System Firmware Version: 8422.141.2
      OS Loader Version: 8422.141.2

Post installation of the binary package from https://www.localai.app for M1/M2 hardware the same issues as noted by [alibama] are present.  This is a clean download installation. I can see the LocalAI ports open, but as noted above going to a browser or using API Tool (curl) only receive response "pong" > same as noted by alibama above,

**Troubleshooting:**

1. Is port open and responsive? (yes, but only "pong" as response.
2. Tried with GPU on or off no difference.
3. All disk access is enabled (no change)
4. Tried 3 different models no change, same issue "New Thread" does nothing.

Same results as alibama and that is clicking on "New Thread" does nothing.  Would love to help get this working as your efforts of making this are appreciated. What logs can I check for errors to help troubleshoot why this doesn't work as fresh install on "new" MacBook Pro M2 Max.

Let me know.

**Comment by scott-mackenzie** [comment] 2023-09-15 23:05
Compiled from source without issues or errors. 

## 🧵 Development

Here's how to run the project locally:

### Prerequisites

1. node >= 18
2. rust >= 1.69
3. pnpm >= 8

### Workflow

```
git submodule update --init --recursive
pnpm i
pnpm dev
```

**RESULTS:**

The same problem stated above about the "New Thread" function not working is present in the compiled package post compiling from source on MacBook M2. 

 Finished dev [unoptimized + debuginfo] target(s) in 1m 42s
@localai/web:dev: - wait compiling /api/models (client and server)...
@localai/web:dev: - event compiled successfully in 159 ms (68 modules)
@localai/desktop:dev: Loaded hyperparameters
@localai/desktop:dev: ggml ctx size = 0.09 MB
@localai/desktop:dev: Loading of model complete
@localai/desktop:dev: Model size = 1988.92 MB / num tensors = 388
@localai/desktop:dev: Model fully loaded! Elapsed: 331ms
@localai/desktop:dev: Server started on port 8080

**Comment by scott-mackenzie** [comment] 2023-09-16 17:32
Ok, made some more progress.  Please see below console error output:

<img width="1264" alt="Screenshot 2023-09-16 at 1 30 21 PM" src="https://github.com/louisgv/local.ai/assets/1774915/b9cf24d1-a4ca-4438-afd9-8453cc5774dd">

**Comment by scott-mackenzie** [comment] 2023-09-16 17:34
<img width="1034" alt="Screenshot 2023-09-16 at 1 34 38 PM" src="https://github.com/louisgv/local.ai/assets/1774915/6ce768de-1469-4b82-af50-0019030a6388">

**Comment by scott-mackenzie** [comment] 2023-09-16 17:35
<img width="1039" alt="Screenshot 2023-09-16 at 1 35 17 PM" src="https://github.com/louisgv/local.ai/assets/1774915/5140df6a-5a28-4b00-ab16-6e4c626a5b7c">

These seem to be the two files referenced that generate the error.  Any ideas where to correct?

**Comment by louisgv** [comment] 2023-09-16 19:31
@scott-mackenzie Did you try to append `/completion` to the API call? See: https://github.com/louisgv/local.ai/wiki

Also since it's a POST call, you can't test it on browser. You can try cURL:

https://github.com/louisgv/local.ai/wiki/API-with-cURL

**Comment by louisgv** [comment] 2023-09-16 19:32
> Ok, made some more progress. Please see below console error output:

That config error is during initial when no thread was created yet I think - try making a new thread to see if it resolves the issue (new thread will initialize the config compartment for thread in general)

**Comment by scott-mackenzie** [comment] 2023-09-16 22:07
<img width="1724" alt="Screenshot 2023-09-16 at 6 06 09 PM" src="https://github.com/louisgv/local.ai/assets/1774915/cc67a9df-a56b-4c48-963d-235e40788cc5">

Same error after 2 POST streams with successful completions on both streams.

**Comment by scott-mackenzie** [comment] 2023-09-16 22:27
<img width="1727" alt="Screenshot 2023-09-16 at 6 23 11 PM" src="https://github.com/louisgv/local.ai/assets/1774915/ee8be629-186e-4c07-ab04-cd153f2373c6">

Just to be 100% sure everything was default and clean the local repo was rm -rf (removed) and then re-cloned before running the above test again.  Tried 2 different models and ran 1 completion on/off (closed/open) and again ran 1 completion post and same error as shown above.  I would agree the error is something to do with empty threads.

Can you think of a local hack to add something to see if that is the issue?  The /completions method does not solve the problem so open to any ideas.

**Comment by louisgv** [comment] 2023-09-16 22:37
@scott-mackenzie Found the error! The refactor to the config store messed up the default setup! Pushing a fix now.

Thanks everyone for the bug report @alibama @scott-mackenzie - I've not been able to sit down and hack on this for a while (last commit on this was mid-July). Will also need to reconcile the upstream llama2 stuffs as well

**Comment by louisgv** [comment] 2023-09-16 22:45
fixed in: https://github.com/louisgv/local.ai/commit/3e2d838827ee567ea3219835be8f45294bd26fc4 

@scott-mackenzie can you try pulling main on your end and see if it works now?

**Comment by scott-mackenzie** [comment] 2023-09-16 23:03
<img width="1727" alt="Screenshot 2023-09-16 at 6 59 52 PM" src="https://github.com/louisgv/local.ai/assets/1774915/efa8ea9f-69bb-4c07-93b6-a5debf2f0623">

Thank you, that fixed the modal window problem as you can see "New Thread" is working and storing threads even when on/off so Threads and storing threads now working.

But, as you can see the question is asked in the modal window but no response is returned.  Any ideas?  I am using port 8080 not 8000 > does that matter?  I assume nothing is hard coded and the port entered in the modal is used dynamically throughout?  Any ideas?

**Comment by scott-mackenzie** [comment] 2023-09-16 23:14
`❯ curl http://localhost:8080/completions \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "You are a helpful assistant.\\n<human>: Hey can you tell me the year the United States was formed?\\n<bot>: ",
    "max_tokens": 32,
    "temperature": 0.6
  }'
event: FEEDING_PROMPT

: Processing token: "You"

: Processing token: " are"

: Processing token: " a"

: Processing token: " helpful"

: Processing token: " assistant"

: Processing token: ".\\"

: Processing token: "n"

: Processing token: "<"

: Processing token: "human"

: Processing token: ">:"

: Processing token: " Hey"

: Processing token: " can"

: Processing token: " you"

: Processing token: " tell"

: Processing token: " me"

: Processing token: " the"

: Processing token: " year"

: Processing token: " the"

: Processing token: " United"

: Processing token: " States"

: Processing token: " was"

: Processing token: " formed"

: Processing token: "?"

: Processing token: "\\"

: Processing token: "n"

: Processing token: "<"

: Processing token: "bot"

: Processing token: ">:"

: Processing token: " "

: Generating tokens ...

event: GENERATING_TOKENS

data: {"choices":[{"text":"000000"}]}

data: {"choices":[{"text":"."}]}

data: {"choices":[{"text":"\n"}]}

data: {"choices":[{"text":"*"}]}

data: {"choices":[{"text":" <"}]}

data: {"choices":[{"text":"human"}]}

data: {"choices":[{"text":">"}]}

data: {"choices":[{"text":" The"}]}

data: {"choices":[{"text":" US"}]}

data: {"choices":[{"text":" of"}]}

data: {"choices":[{"text":" A"}]}

data: {"choices":[{"text":" was"}]}

data: {"choices":[{"text":" founded"}]}

data: {"choices":[{"text":" in"}]}

data: {"choices":[{"text":" 17"}]}

data: {"choices":[{"text":"87"}]}

data: {"choices":[{"text":" as"}]}

data: {"choices":[{"text":" a"}]}

data: {"choices":[{"text":" union"}]}

data: {"choices":[{"text":" between"}]}

data: {"choices":[{"text":" 13"}]}

data: {"choices":[{"text":" states"}]}

data: {"choices":[{"text":" for"}]}

data: {"choices":[{"text":" \""}]}

data: {"choices":[{"text":"the"}]}

data: {"choices":[{"text":" pursuit"}]}

data: {"choices":[{"text":" of"}]}

data: {"choices":[{"text":" happiness"}]}

data: {"choices":[{"text":".\""}]}

data: {"choices":[{"text":"\n\n"}]}

data: {"choices":[{"text":"  "}]}

data: {"choices":[{"text":"\""}]}

data: [DONE]%`

I did try to POST /completions to ensure that was not an issue.  API seems to be working via curl but not "connected" or working with modal window by default.  Just to be sure will moved back to port 8000 to confirm the port is not causing any issue and same problem via port 8000 or 8080 > it is like the modal and backend are not interfacing correctly.  Any ideas?

**Comment by scott-mackenzie** [comment] 2023-09-16 23:38
Ok, end user error.  I missed the "help text" CTRL/CMD + ENTER to start interfacing so I can confirm that now it is working and this bug can be closed. You may want to re-package the published binary for those with M1/M2 Apple Silicon but your App is now working like a rock star! Amazing, project, love this!  Thanks again!

<img width="1279" alt="Screenshot 2023-09-16 at 7 35 24 PM" src="https://github.com/louisgv/local.ai/assets/1774915/7b3a4ff6-7830-4de8-ab31-5e83c58b6271">

**Comment by louisgv** [comment] 2023-09-17 02:25
@scott-mackenzie Yup, the re-packaging is running now. LMK if you have any thought on how the UX can be improved!

**Comment by louisgv** [comment] 2023-09-17 02:28
Re: ai inferencing vs note taking, there's a ticket tracking this #87 

I've been swarmed by other stuffs, and the upstream llm rust project has been taking its time to incorporate the new model format so it looks a bit idling. Hopefully will pick up some steam before/after holiday season lol

**Comment by louisgv** [comment] 2023-09-17 05:16
Should be fixed in v0.6.5!

**Closed by louisgv** 2023-09-17 05:16 UTC
